<a href="https://colab.research.google.com/github/Anu2813/colab-notebook-demo/blob/main/ICP3_PART1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.random.randint(1, 21, size=15)
print("Original Array (1D):")
print(arr)

Original Array (1D):
[16 15 18 20  2  9  1 10 20  8 16 15 13 18  8]


In [2]:
reshaped = arr.reshape(3, 5)
print("\nReshaped Array (3x5):")
print(reshaped)


Reshaped Array (3x5):
[[16 15 18 20  2]
 [ 9  1 10 20  8]
 [16 15 13 18  8]]


In [3]:
print("\nShape of the array:", reshaped.shape)


Shape of the array: (3, 5)


In [4]:
for i in range(reshaped.shape[0]):
    max_index = np.argmax(reshaped[i])
    reshaped[i][max_index] = 0

print("\nModified Array (Max in each row replaced with 0):")
print(reshaped)


Modified Array (Max in each row replaced with 0):
[[16 15 18  0  2]
 [ 9  1 10  0  8]
 [16 15 13  0  8]]


In [8]:
array_b = np.ones((4, 3), dtype=np.int32)

print("\n2D Array of size 4x3:")
print(array_b)

print("Shape:", array_b.shape)
print("Type:", type(array_b))
print("Data type:", array_b.dtype)



2D Array of size 4x3:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [9]:
matrix_c = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(matrix_c)

print("\nEigenvalues:")
print(eigenvalues)

print("Right Eigenvectors:")
print(eigenvectors)



Eigenvalues:
[2. 1.]
Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [10]:
matrix_d = np.array([[0, 1, 2], [3, 4, 5]])
diagonal_sum = np.trace(matrix_d[:, :2])

print("\nSum of diagonal elements:")
print(diagonal_sum)


Sum of diagonal elements:
4


In [11]:
original = np.array([[1, 2], [3, 4], [5, 6]])
reshaped_e = original.reshape(2, 3)

print("\nOriginal 3x2 array:")
print(original)

print("Reshaped to 2x3:")
print(reshaped_e)


Original 3x2 array:
[[1 2]
 [3 4]
 [5 6]]
Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
